language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install redis
install: "pip install -r requirements.txt"
script: python -m unittest discover
notifications:
  email:
    recipients:
      - theepicsnail@gmail.com
  irc:
    channels:
      - "udderweb.com:7777#paest"
    template:
      - "%{author}, %{message}. %{compare_url}"
      - "Build details: %{build_url}"
